name: Grammar Check for LaTeX

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      run: |
        # Percorsi file personalizzati
        PERSONAL_WORDLIST_IT=".github/workflows/Dizionari_Latex/personal_wordlist_it.txt"
        PERSONAL_WORDLIST_EN=".github/workflows/Dizionari_Latex/personal_wordlist_en.txt"

        # Verifica che i file di parole personalizzate esistano
        if [ ! -f "$PERSONAL_WORDLIST_IT" ] || [ ! -f "$PERSONAL_WORDLIST_EN" ]; then
          echo "Uno o più file di parole personalizzate non trovati!"
          exit 1
        fi

        # Crea file temporaneo per le parole non riconosciute
        TMP_FILE=$(mktemp)

        # Processa tutti i file .tex
        for file in $(find . -name "*.tex"); do
          echo "Processing $file..."
          sed -E '
            s/\\[a-zA-Z@]+(\[[^]]*\])?(\{[^}]*\})?//g; # Comandi base
            s/\\begin\{[^}]*\}//g;                    # Inizio ambienti
            s/\\end\{[^}]*\}//g;                      # Fine ambienti
            s/\$[^\$]*\$//g;                          # Equazioni inline
            s/\$\$[^\$]*\$\$//g;                    # Equazioni display
            s/%.*//g;                                   # Commenti
            s/[{}]//g;                                  # Brackets
          ' "$file" | aspell --lang=it --add-words="$PERSONAL_WORDLIST_IT" list >> $TMP_FILE
        done

        # Controlla le parole non riconosciute in italiano
        if [ -s "$TMP_FILE" ]; then
          echo "Checking unrecognized words in English..."
          sort -u "$TMP_FILE" | aspell --lang=en --add-words="$PERSONAL_WORDLIST_EN" list > errors_in_english.txt

          if [ -s errors_in_english.txt ]; then
            echo "Errors found:"
            cat errors_in_english.txt
            exit 1
          else
            echo "No errors found in English. Only unrecognized Italian words."
          fi
        else
          echo "No errors found in Italian."
        fi