name: Controllo ortografico file LaTeX

on:
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  controllo_grammaticale:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_CONTR_GRAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch branch remote
        run: |
          git fetch origin develop
          git branch --set-upstream-to=origin/develop develop

      - name: Installa aspell
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-it

      - name: Controllo grammaticale
        run: |
          python3 .github/workflows/dipendenze/controlloOrtografico.py
        working-directory: .

      - name: Aggiunge alla PR il commento con errori
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F errori.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
