name: Pubblicazione dei documenti LaTeX compilati nel repository Documentazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIRS_TO_IGNORE: ${{vars.DIRS_TO_IGNORE}}
            DIRS_TO_DEL: ${{vars.DIRS_TO_DEL}}
            
        runs-on: ubuntu-latest
        steps:
            - name: Clona la repository dei documenti sorgenti
              uses: actions/checkout@v4
              with:
                path: src

            - name: Clona la repository dei documenti compilati
              uses: actions/checkout@v4
              with:
                repository: https://github.com/ALT-F4-eng/Documentazione
                path: dst
                token: ${{ secrets.PAT_COMPILATI }}
            
            - name: Seleziona i documenti da compilare
              id: setup_tex
              run: |
                    echo "TEX_PATH<<EOF" >> $GITHUB_OUTPUT
                    echo "$(find -type f -name "*.tex" | grep -v $(echo ${DIRS_TO_IGNORE} ${DIRS_TO_DEL}| sed 's/ /\\|/g'))" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  
            - name: Compila i documenti
              uses: xu-cheng/latex-action@v3
              with:
                work_in_root_file_dir: true
                root_file: |
                    ${{ steps.setup_tex.outputs.TEX_PATH }}
      
            - name: Rimuove file inutili in src
              run: |
                cd src
                rm -rf $DIRS_TO_DEL
                find * -type f ! -name "*.pdf" -delete
                cd ..
                
            - name: Copia le cartelle da ignorare
              run: |
                  i=0
                  for d in $DIRS_TO_IGNORE; do
                    dest_dirs=$(find ./dst -type d -name "*${d}")
                    src_dirs=($(find ./src -type d -name "*${d}"))
                    for dest_dir in $dest_dirs; do
                        cp -rf $dest_dir "${src_dirs[$i]}/.."
                        i=$((i + 1)) 
                    done
                  done

            - name: Pulizia dell'intera repo di destinazione
              run: rm -rf dst/*
              
            - name: Copia i documenti nella repo di destinazione
              run: cp -r src/* dst
            
            - name: Commit dei documenti compilati
              uses: EndBug/add-and-commit@v9
              with:
                committer_email: altf4.eng@gmail.com
                committer_name: altf4
                cwd: dst
